### ISSUE TITLE
 "Exception unhandled: InvalidGraphDef ".Error when trying inception demo with own trained model

### ISSUE THREAD

**Issue by fastlater** [emgucv/emgutf#3]
Hi emguTF community,

I used the retrain.py script to retrain the inception v3 model for the flowers classification demo and I got 2 files: trained_graph.pb and trained_labels.txt. Using freeze.py, I can export the frozen model. When I used the retrain_model_classifier.py, the classification is correct using my exported model and the frozen model thus I am sure my pb and txt files are good.

Then, I tried to get the classification result using the Inception demo and I got the error "Exception unhandled: InvalidGraphDef "  calling the function Emgu.TF.Graph.ImportGraphDef(Buffer graphDef, ImportGraphDefOptions options, Status status)

I tried with a simple demo like this in python:
    a = tf.placeholder(tf.int32, name="input_a")
    b = tf.placeholder(tf.int32, name="input_b")
    mul = tf.multiply(a, b,name="op_Mul")
then get the frozen graph and the function does not show error. Why using the same code lines, I get error using my trained inception model? What is the meaning of this error? Any suggestion about how to export correctly the models?

**Comment by fastlater** [comment]
any update?

**Comment by emgucv** [comment]
Hi, I have tried to re-train the flower model myself and can re-produce your issue. 

A little investigation into it I found that this is related to the following bug:
https://github.com/tensorflow/tensorflow/issues/582
when tensorflow failed to import any model larger than 64MB due to a bug in protobuf. 

The bug was fixed in the bazel build but is not fixed in the cmake build. 

We fix it in this commit 70c746cc960483d0c197ec41439d9b031bd35186 by switching the build script to use bazel instead of cmake in Windows.

**Comment by emgucv** [comment]
I have added a tutorial page with instructions here:
http://www.emgu.com/wiki/index.php/Training_Inception_Model
I will required a new Emgu TF 1.3.0 build, to be release soon...

**Comment by fastlater** [comment]
Thank you so much for your reply. I spent several days trying many different ways to make it work but always failed with inception. Now, I know why. 
I will be waiting for the 1.3.0 build.

**Comment by fastlater** [comment]
I just tested the new 1.3 build. Now, it is working perfectly. Thank you for fix the bug.

**Comment by fastlater** [comment]
@emgucv  I go forward and now I tried with other bigger models such as object detection models. However, again, I get the in Invalid GraphDef error. Is there a way to check what is wrong with the input? The .pb is 232Mb. You said the new 1.3 version will have no problem with heavy files so I guess there should be something else. Can you give me some hints about how to solve this kind of error.

**Comment by AdamStefan** [comment]
Hi, we are facing the same problem, we are not able to load our model ("Invalid GraphDef" error) . We are using the version 1.4 with CUDA support for Windows. Our model was derived from Resnet50 and has 112 MB.

**Comment by emgucv** [comment]
Hmm, I am able to reproduce that, it seems that the bug is back for the 1.4 CUDA release. I will be working on a fix.

**Comment by AdamStefan** [comment]
Hi, is there any update about this issue?

**Comment by neoyero** [comment]
Hi, is there any update about this issue?

**Comment by emgucv** [comment]
Fixed in this commit: 7d15c5ec7455a6d7a8c45b6dd42897f288cd123b
Please use 1.3.0.50-rc1 or wait for a new release to include the above commit.

**Comment by AdamStefan** [comment]
Hi, when do you plan to release the new version?

**Comment by neoyero** [comment]
Hello, I will be more explicit in my explanation,
I want to use tensorflow from c#, I have downloaded the tensorflow library, I have used retrain.py with the python command, with a set of 60 images, with variable dimensions but all in gray scale, I have done the training with 20,000 stages , this process was successful, and I generated the files output_graph.pb and output_labels.txt, then I created a project in c # VS 2015 in which I imported the NuGet emgu.tf 1.4.1.88 and when I try to import the aforementioned files, it launches the Invalid GraphDef error , in the NuGet it says that Emgu.TF is a higher version than the one that they recommend me, but it still gives me the same error, I'm really new to this topic, please help me !!!!!!...

**Comment by compustar** [comment]
Got the same issue with the NuGet 1.4.1.88 package. The 64MB limitation is still there:
[libprotobuf ERROR C:\Buildbot\Slave\tf_x64\build\tensorflow\tensorflow\contrib\
cmake\build\protobuf\src\protobuf\src\google\protobuf\io\coded_stream.cc:208] A
protocol message was rejected because it was too big (more than 67108864 bytes).
  To increase the limit (or to disable these warnings), see CodedInputStream::Se
tTotalBytesLimit() in google/protobuf/io/coded_stream.h.

**Comment by LizaBlignaut** [comment]
Hello
I am using the newest package 1.5.0.129 and when I try to load a model larger than 64 MB I still get the error:
[libprotobuf ERROR C:\Buildbot\Slave\tf_x64\build\tensorflow\tensorflow\contrib\cmake\build\protobuf\src\protobuf\src\google\protobuf\io\coded_stream.cc:208] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.

Is there a fix for this error?

**Comment by emgucv** [comment]
Closing ticket now. The current release v2.4 can load tf models larger than 64MB.
